# Generated by Django 2.2 on 2019-10-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dairyform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='farmer',
            name='LastName',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='Age',
            field=models.CharField(max_length=20),
        ),
    ]
